---
title: "This is a Template"
author: "Denis Ostroushko"
date: '`r Sys.Date()`'
output: 
  flexdashboard::flex_dashboard:
    theme: journal
    source_code: embed
---

```{r packages }

library(ggthemes, quietly = TRUE)
library(htmltools, quietly = TRUE)
library(tidyverse)
library(plotly)
library(flexdashboard)
library(ggsoccer)
library(googleAuthR)
library(googlesheets4)

```

```{r}

scores <- 
  read_sheet("https://docs.google.com/spreadsheets/d/1xy6CVRLfpO2tsVxcl5ZlwOGvqqlTipfcC4T4YBgM8ZY/edit#gid=0", 
             sheet = "Knights")

schedule <- 
  read_sheet("https://docs.google.com/spreadsheets/d/1xy6CVRLfpO2tsVxcl5ZlwOGvqqlTipfcC4T4YBgM8ZY/edit#gid=0", 
             sheet = "Schedule")

```

```{r}
ast <- scores %>% filter(Action == "Assist")

linkups <- 
  scores %>% filter(Action == "Goal") %>% 
    select(Date, Opponent, Score, Player, `Player Position`, `Play Type`) %>% 
    rename(Scorer = Player) %>% 
  
  left_join(
    scores %>% filter(Action == "Assist") %>% 
      select(Date, Opponent, Score, Player) %>% 
      rename(Assister = Player), 
    
    by = c("Date", "Opponent", "Score")
  )

View(linkups)

```

```{r}
linkups %>% 
  group_by(Assister) %>% 
  summarise(total_assist = n()) %>% 
  filter(!is.na(Assister)) %>% 
  
  left_join(
    linkups %>% 
      group_by(
        Assister, Scorer
      ) %>% 
      summarise(
        person_assists = n()
      ), 
    
    by = "Assister"
  ) %>% 
  
  arrange(-total_assist , Assister)

```

```{r}

scores %>% 
  filter(Action == "Goal") %>% nrow()

scores %>% 
  filter(Action == "Assist") %>% nrow()

```

```{r}

scores %>% 
  filter(Action == "Assist") %>% 
  group_by(`Pass Type`) %>% 
  summarize(n = n(), 
            p = n()/nrow(.)) %>% 
  arrange(-n)
```

```{r}

scores %>% 
  filter(Action == "Assist") %>% 
  group_by(`Player`) %>% 
  summarize(n = n(), 
            p = n()/nrow(.)) %>% 
  arrange(-n)

scores %>% 
  filter(Action == "Goal") %>% 
  group_by(`Player`) %>% 
  summarize(n = n(), 
            p = n()/nrow(.)) %>% 
  arrange(-n)
```

```{r}

scores %>% 
  filter(Action == "Assist") %>% 
  group_by(`Field Part`) %>% 
  summarize(n = n(), 
            p = n()/nrow(.)) -> 
  
  assists

assists <- assists %>% arrange(`Field Part`)

assists$y_lab = c(85,50,15)
assists$x_lab = c(75,75,75)

assists$label = with(assists, paste0(n, " (", round(p, 4)*100, "%)"
                                     )
                     )

```

```{r}

ggplot(data = assists, 
       aes(x = x_lab, y = y_lab, label = label)) +
  annotate_pitch() +
  theme_pitch() + 
  geom_point(color = "white") + 
  geom_text(size=10) + 
  
  geom_segment(
    x = 30, xend = 80, 
    y = 67, yend = 67,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    linetype = "dashed", 
    size = 2, 
    arrow = arrow(length = unit(0.3, "inches")),
    colour = "blue" # Also accepts "red", "blue' etc
  )+ 
  
  geom_segment(
    x = 30, xend = 80, 
    y = 33, yend = 33,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    linetype = "dashed", 
    size = 2, 
    arrow = arrow(length = unit(0.3, "inches")),
    colour = "blue" # Also accepts "red", "blue' etc
  )
```