---
title: "MRSL D2 Knights 2023"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    vertical_layout: fill
---

<!--------------------------------------------------------------------------------------
                                  SET UP: PACKAGES, FUCNTIONS, DATA LAOD 
------------------------------------------------------------------------------------> 

```{r}
knitr::opts_chunk$set(
  echo = F, warning = F, message = F
)
```

```{r packages }

library(ggthemes, quietly = TRUE)
library(htmltools, quietly = TRUE)
library(tidyverse)
library(plotly)
library(flexdashboard)
library(ggsoccer)
library(googleAuthR)
library(googlesheets4)
library(kableExtra)
library(shinydashboard)
library(scales)

```

```{r}
int_breaks <- function(x, n = 5) {
  l <- pretty(x, n)
  l[abs(l %% 1) < .Machine$double.eps ^ 0.5] 
}
```

```{r laod goals and assists data}

scores <- 
  read_sheet("https://docs.google.com/spreadsheets/d/1xy6CVRLfpO2tsVxcl5ZlwOGvqqlTipfcC4T4YBgM8ZY/edit#gid=0", 
             sheet = "Knights")

scores$Group <- 
  with(scores, 
       case_when(
         `Player Position` %in% c("LW", "RW", "ST") ~ "Attackers", 
         `Player Position` %in% c("CM") ~ "Midfielders", 
         T ~ "Defenders"
       ))

scores$Group <- factor(scores$Group, levels = c("Defenders", "Midfielders", "Attackers"))

```

```{R load schedule and resutls data}
schedule <- 
  read_sheet("https://docs.google.com/spreadsheets/d/1xy6CVRLfpO2tsVxcl5ZlwOGvqqlTipfcC4T4YBgM8ZY/edit#gid=0", 
             sheet = "Schedule")

schedule <- 
  schedule %>% 
  filter(Division == "D2" & !is.na(`Final Score` )) %>% 
  mutate(
    game = seq(from = 1, to = nrow(.), by = 1)
  )

schedule$`Home Score` = with(schedule, substr(`Final Score`, 2, 2))
schedule$`Home Score` <- as.numeric(schedule$`Home Score`)

schedule$`Away Score` = with(schedule, substr(`Final Score`, 4, 4))
schedule$`Away Score` <- as.numeric(schedule$`Away Score`)

schedule$our_goals = 
  with(schedule, 
       case_when(
         Home == "Knights" ~ `Home Score`, 
         T ~ `Away Score`
       ))
schedule$our_conceded = 
  with(schedule, 
       case_when(
         Home == "Knights" ~ `Away Score`, 
         T ~ `Home Score`
       ))

schedule$opponent = 
  with(schedule, 
       case_when(
         Home == "Knights" ~ Away, 
         T ~ Home
       ))

```

<!--------------------------------------------------------------------------------------
                                            DASHBOARD BODY
------------------------------------------------------------------------------------> 

Team Performance 
===

Column {data-width=200}
---

<!-- 
VALUE BOXES 
--> 

### Box

```{R}

Goals <- scores %>% filter(Action == "Goal") %>% nrow()
Games <- schedule %>% filter(Division == "D2") %>% nrow()

val <- 
  round(Goals / Games , 2)

cap <- paste0("Scored Goals Per Game <br/>", Goals, " goals in ", Games, " games")

flexdashboard::valueBox(value = val, caption = cap, color = "green")
```

### Box

```{R}

val <- scores %>% filter(Action == "Goal") %>% select(Player) %>% unique() %>% nrow()

cap <- paste0("Players with 1+ Goals")

flexdashboard::valueBox(value = val, caption = cap, color = "cyan")
```

### Box

```{R}

Goals <- schedule %>% filter(Division == "D2") %>% summarize(sum(our_conceded)) %>% unlist()
Games <- schedule %>% filter(Division == "D2") %>% nrow()

val <- 
  round(Goals / Games , 2)

cap <- paste0("Allowed Goals Per Game <br/>", Goals, " goals in ", Games, " games")

flexdashboard::valueBox(value = val, caption = cap, color = "orange")
```

Column {data-width=450 }
---

### Goals Origin By Position

```{r ,fig.width=10}

scores %>% 
  filter(Action == "Goal") %>% 
  group_by(`Group`) %>% 
  summarize(n = n(), 
            p = n()/nrow(.)) -> 
  
  goals

goals <- goals %>% arrange(`Group`)

goals$y_lab = c(50,75)
goals$x_lab = c(50,85)

goals$label = with(goals, paste0(n, " (", round(p, 4)*100, "%)"
                                     )
                     )


ggplot(data = goals, 
       aes(x = x_lab, y = y_lab, label = label)) +
  annotate_pitch(colour = "#999e9b") +
  theme_pitch(aspect_ratio = NULL) + 
  geom_point(color = "white") + 
  geom_text(size=12) + 
  
  geom_segment(
    x = 67, xend = 67, 
    y = 10, yend = 90,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    linetype = "dashed", 
    size = 2, 
    colour = "red" # Also accepts "red", "blue' etc
  )+ 
  
  geom_segment(
    x = 31, xend = 31, 
    y = 10, yend = 90,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    linetype = "dashed", 
    size = 2, 
    colour = "red" # Also accepts "red", "blue' etc
  ) + 
  
  geom_segment(
    x = 15, xend = 25, 
    y = 85, yend = 85,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.1, "inches")),
    colour = "#7fb550" # Also accepts "red", "blue' etc
  ) + 
  
  geom_segment(
    x = 45, xend = 55, 
    y = 85, yend = 85,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.1, "inches")),
    colour = "#7fb550" # Also accepts "red", "blue' etc
  )+ 
  
  geom_segment(
    x = 75, xend = 85, 
    y = 85, yend = 85,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.1, "inches")),
    colour = "#7fb550" # Also accepts "red", "blue' etc
  ) + 
  
  theme(text = element_text(size = 20))
```

### Assists origin By Position

```{r,fig.width=10}
scores %>% 
  filter(Action == "Assist") %>% 
  group_by(`Group`) %>% 
  summarize(n = n(), 
            p = n()/nrow(.)) -> 
  
  assists2

assists2 <- assists2 %>% arrange(`Group`)

assists2$y_lab = c(25,50,75)
assists2$x_lab = c(15,50,85)

assists2$label = with(assists2, paste0(n, " (", round(p, 4)*100, "%)"
                                     )
                     )


ggplot(data = assists2, 
       aes(x = x_lab, y = y_lab, label = label)) +
  annotate_pitch(colour = "#999e9b") +
  theme_pitch(aspect_ratio = NULL) + 
  geom_point(color = "white") + 
  geom_text(size=12) + 
  
  geom_segment(
    x = 67, xend = 67, 
    y = 10, yend = 90,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    linetype = "dashed", 
    size = 2, 
    colour = "red" # Also accepts "red", "blue' etc
  )+ 
  
  geom_segment(
    x = 31, xend = 31, 
    y = 10, yend = 90,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    linetype = "dashed", 
    size = 2, 
    colour = "red" # Also accepts "red", "blue' etc
  ) + 
  
  geom_segment(
    x = 15, xend = 25, 
    y = 85, yend = 85,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.1, "inches")),
    colour = "#7fb550" # Also accepts "red", "blue' etc
  ) + 
  
  geom_segment(
    x = 45, xend = 55, 
    y = 85, yend = 85,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.1, "inches")),
    colour = "#7fb550" # Also accepts "red", "blue' etc
  )+ 
  
  geom_segment(
    x = 75, xend = 85, 
    y = 85, yend = 85,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    size = 1, 
    arrow = arrow(length = unit(0.1, "inches")),
    colour = "#7fb550" # Also accepts "red", "blue' etc
  )
```

### Assists Origin By Direction

```{r,fig.width=10}
scores %>% 
  filter(Action == "Assist") %>% 
  group_by(`Field Part`) %>% 
  summarize(n = n(), 
            p = n()/nrow(.)) -> 
  
  assists

assists <- assists %>% arrange(`Field Part`)

assists$y_lab = c(85,50,15)
assists$x_lab = c(75,75,75)

assists$label = with(assists, paste0(n, " (", round(p, 4)*100, "%)"
                                     )
                     )


ggplot(data = assists, 
       aes(x = x_lab, y = y_lab, label = label)) +
  annotate_pitch(colour = "#999e9b") +
  theme_pitch(aspect_ratio = NULL) + 
  geom_point(color = "white") + 
  geom_text(size=12) + 
  
  geom_segment(
    x = 30, xend = 89, 
    y = 67, yend = 67,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    linetype = "dashed", 
    size = 2, 
    arrow = arrow(length = unit(0.3, "inches")),
    colour = "blue" # Also accepts "red", "blue' etc
  )+ 
  
  geom_segment(
    x = 30, xend = 89, 
    y = 33, yend = 33,
    lineend = "round", # See available arrow types in example above
    linejoin = "round",
    linetype = "dashed", 
    size = 2, 
    arrow = arrow(length = unit(0.3, "inches")),
    colour = "blue" # Also accepts "red", "blue' etc
  )
```

Column {data-width=400}
---

### Goal Differential Through the Season

```{r differential over timeline }

schedule %>% 
  mutate(
    goals_for = cumsum(our_goals), 
    goals_against = cumsum(our_conceded), 
    
    differential = goals_for - goals_against
  ) %>% 
  select(game, Date, goals_for, goals_against, differential, opponent) %>% 
  
  pivot_longer(
    cols = c("goals_for", "goals_against"), 
    values_to = "Val", 
    names_to = "Type"
  ) %>% 
  
  mutate(
    Type = case_when(
      Type == "goals_for" ~ "Goals Scored", 
      T ~ "Goals Conceded"
    )
  ) -> plot_df

plot_df %>% 
  plot_ly(
    x = ~game,
    y = ~Val,
    color = ~Type,
    colors = c("red", "#36c959"),
    
    type = "scatter",
    mode = "lines+markers", 
    
    text = 
      with(. , 
           paste(
             "Date: ", Date, 
             "<br>Opponent: ", opponent, 
             "<br>Goals:", Val, 
             "<br>Type: ", Type, 
             "<br>Differential", differential
    )), 
    
    hoverinfo = "text"
  ) %>% 
  layout(
    yaxis = list(
      range = c(0, max(cumsum(schedule$our_goals)) + 1), 
      title = "Goals For and Against"
    ), 
    xaxis = list(
      title = "Game #"
    ), 
    legend = list(
      orientation = "h", y = -.5
      )
    )


```

### Goal Differential Distribution By Game

```{r , fig.width=8, fig.height=7}

schedule %>% 
  mutate(
    differential = our_goals - our_conceded
  ) -> schedule

schedule %>% 
  ggplot(aes(x = differential)) + 
  geom_histogram(
    binwidth = 1, 
    color = "grey", 
    fill = "blue"
    ) + 
  
  scale_x_continuous(
    labels = seq(from = min(schedule$differential), 
                 to =  max(schedule$differential), 
                 by = 1),
    
    breaks = seq(from = min(schedule$differential), 
                 to =  max(schedule$differential), 
                 by = 1)
  ) + 
  
  scale_y_continuous(
    breaks = function(x) int_breaks(x, n = 10)
  ) + 
  
  theme_minimal() + 
  
  xlab("Goal Differential") + 
  ylab("Count") + 
  
  ggtitle(
    paste0("Average per Game: +", 
          round(mean(schedule$differential), 4))
  ) + 
  
  theme(text = element_text(size = 20))

```

Row {data-width=250}
-------------------------------------

### Goals and Assist Details 

```{r}
custom_page_1_font = 14
```

```{r }

scores %>% 
  filter(Action == "Goal") %>% 
  group_by(`Shot Type`) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  rename(
    Type = `Shot Type`
  ) %>% 
  mutate(id = seq(from = 1, to = nrow(.), by = 1)) -> shot_types

n_shot_types <- nrow(shot_types)

scores %>% 
  filter(Action == "Goal") %>% 
  group_by(`Position`) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  rename(
    Type = `Position`
  ) %>% 
  mutate(id = seq(from = 1, to = nrow(.), by = 1)) -> shot_loc

n_shot_loc <- nrow(shot_loc)

shot_sum <- merge(shot_types, shot_loc, by = "id", all = T) %>% select(-id)

shot_sum <- 
  shot_sum %>% 
  mutate_all(as.character)

shot_sum <- 
  shot_sum %>% 
    mutate_all(~replace(., is.na(.), ""))

shot_sum %>% 
  kable(align = c('l', 'c', 'l', 'c'), 
        col.names = c("Goal Shot Type", "N", "Goal Location", "N")) %>% 
  kable_styling(bootstrap_options = c("condesed", "striped"),
                font_size = custom_page_1_font) 


```

```{r}

scores %>% 
  filter(Action == "Assist") %>% 
  group_by(`Pass Type`) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  rename(
    Type = `Pass Type`
  ) %>% 
  mutate(id = seq(from = 1, to = nrow(.), by = 1))-> pass_types

n_shot_types <- nrow(pass_types)

scores %>% 
  filter(Action == "Assist") %>% 
  group_by(`Position`) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  rename(
    Type = `Position`
  ) %>% 
  mutate(id = seq(from = 1, to = nrow(.), by = 1)) -> pass_loc

n_shot_loc <- nrow(pass_loc)

shot_sum <- merge(pass_types, pass_loc, by = "id", all = T) %>% select(-id)

shot_sum <- 
  shot_sum %>% 
  mutate_all(as.character)

shot_sum <- 
  shot_sum %>% 
    mutate_all(~replace(., is.na(.), ""))

shot_sum %>% 
  kable(align = c('l', 'c', 'l', 'c'),  
        col.names = c("Assist Pass Type", "N", "Assist Location", "N")) %>% 
  kable_styling(bootstrap_options = c("condesed", "striped"),
                font_size = custom_page_1_font) 

```

Individual Performance 
===